services:
  psql_auth:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - back-net
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - back-net
    ports:
      - "6379:6379"
    command: redis-server --requirepass password

networks:
  back-net:
    driver: bridge

volumes:
  psql_volume: